name: "\U0001F41E バグテンプレート"
description: バグをレポートする
labels: ["バグ", "👩🏻‍💼 起票"]

body: 
- type: textarea
  attributes:
    label: 概要
  validations:
    required: true

- type: textarea
  attributes:
    label: 再現するのに必要な動作
    description: 再現するのに必要な動作をできるたけ詳細に記述します。
    value: |
        1. 
    render: markdown
  validations:
    required: true

- type: textarea
  attributes:
    label: 期待する動作
    description: 最終的にどのような動作を期待するかを記述します。
    render: markdown
  validations:
    required: true

- type: textarea
  attributes:
    label: スクリーンショット
    description: 再現したスクリーンショットを追加します。
    render: markdown
  validations:
    required: false

- type: checkboxes
  attributes:
    label: 動作環境
    description: 発生した環境を選択します。
    options:
    - label: DEV
    - label: UT
    - label: ACT
  validations:
    required: false

- type: textarea
  attributes:
    label: 備考
    render: markdown
  validations:
    required: false
