name: Build and Push Docker Images
on:
  push:
    branches:
      - master
    paths:
      - "docker/**"
      - ".github/workflows/build_and_push_docker.yml"

jobs:
  determine-changes:
    runs-on: ubuntu-latest
    outputs:
      changed_dirs: ${{ steps.set-output.outputs.changed_dirs }}
    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 変更があったフォルダを取得
      - name: Get changed directories
        id: set-output
        run: |
          CHANGED_DIRS=$(git log -m -1 --name-only --pretty="" | grep '^docker/' | cut -d'/' -f2 | sort -u | jq -R -s -c 'split("\n")[:-1]')
          echo "${CHANGED_DIRS}"
          echo "changed_dirs=${CHANGED_DIRS}" >> $GITHUB_OUTPUT

  build-and-push:
    needs: determine-changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      matrix:
        dir: ${{ fromJson(needs.determine-changes.outputs.changed_dirs) }}
    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      # DockerHubにログイン
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.OWNER_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Dockerビルドとプッシュのセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # DockerイメージのビルドとPush
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./docker/${{ matrix.dir }}
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/${{ matrix.dir }}:latest
          provenance: false
